server:
  port: 8060
  servlet:
    context-path: /fromzerotoexpert
spring:
  datasource:
    url: jdbc:mysql://47.98.198.2:3306/from_zeroto_expert?characterEncoding=utf8&useSSL=false&serverTimezone=CST&rewriteBatchedStatements=true
    username: wcx
    password: 123456
redis:
  host: 127.0.0.1
  port: 6379
  jedis:
    pool:
      #最大连接数
      max-active: 8
      #最大阻塞等待时间(负数表示没限制)
      max-wait: -1
      #最大空闲
      max-idle: 8
      #最小空闲
      min-idle: 0
  #连接超时时间
  timeout: 30000
